### ISSUE TITLE
Not updating menu values after function call

### ISSUE THREAD

**Issue by ConnalM** [KrisKasprzak/Adafruit_ST7735_Menu#3]
Hi,

I'm using your menu very successfully (thanks!) but I have hit a problem that I can't seem to resolve. It looks like it should work but I can't see why it doesn't, so, I'm after help, please.

I have a function to set up the menu as follows:

```
WifiOption1 = WifiMenu.addNI("SSID",    0,                 0,        sizeof(SSIDArray)/sizeof(SSIDArray[0]), 1,          0,              SSIDArray);
WifiOption2 = WifiMenu.addNI("FW ",     FIRMWARE_VERSION,  0,        1,                                      0,          1,              NULL);
WifiOption3 = WifiMenu.addNI("Reset",   0,                 0,        sizeof(NoYes) / sizeof(NoYes[0]),      1,          0,              NoYes);

```
(I have other questions about this but not at the moment).

In the ProcessWifiMenu() function, when I change the value of WifiOption3 (on the menu) to 1 (ie 'Yes'), it calls a function called configWifi(), using the following relevant lines of code:

```
ProcessWifiMenu()
{
   if (EditMenuOption == WifiOption3) 
      {
        if (WifiMenu.value[WifiOption3] == 1) 
        {
          configWifi();
          WifiMenu.value[WifiOption3] = 0;
          Display.fillScreen(MENU_BACKGROUND);
          WifiMenu.draw();
        }
      }
}
```

When it returns from processing this function, I set the value of WifiOption3 to be 0 (ie 'No) (it shows as 0.00 - shouldn't it be an integer?) as  it should be but the menu is showing  'Yes' still (yes/true/1). Setting WifiMenu.draw() doesn't make any difference. I've tried a number of different things but I can't make it update. 

Even exiting the menu and re-entering it doesn't update the values.

Any thoughts?

I'm happy to send you my entire code, if that makes life easier for you.

Thanks,

Connal

**Comment by KrisKasprzak** [comment]
It would be easiest if you can send me your code. If you want to send privately you can send it to

What MCU are you using?

Also the value property is a float. you are right yes / not should be a bool or a byte. However this menu system was designed to handle bytes to floats, so I made all properties float, user just needs to type case if they need byte ( byte Myval =  (byte) WifiMenu.value[WifiOption3].value;

**Comment by ConnalM** [comment]
Hi,

Attached is my code. I made a few small differences to your library, so
there are a couple of tweaks to how I call it. It doesn't make any
functional changes but I can send you my version of your library (or put it
on github), if that would help?

Thanks for your help on this.

Connal

**Comment by ConnalM** [comment]
PS. it's an Esp32

**Comment by KrisKasprzak** [comment]
Rats...yahoo stripped everything out so there was no included code.

try again?

**Comment by ConnalM** [comment]
Hi,

I have sent an invitation to my repository

Connal

**Comment by ConnalM** [comment]
And also zipped here. Password is 'kriskasp'

**Comment by KrisKasprzak** [comment]
ahhh.. Now I see what you are trying to do.. basically when a menu item is set to "Yes" run some code, then set that menu item back to "No". The library supports this but you will need to use the SetItemValue(id, value); method

The .value property was intended to be a "get the value", and I see how this caused confusion. I may change the lib such that value will actually change the row data 

WifiMenu.SetItemValue(WifiOption3, 0);

// hence your code would be
ProcessWifiMenu()
{
   if (EditMenuOption == WifiOption3) 
      {
        if (WifiMenu.value[WifiOption3] == 1) 
        {
          configWifi();
          WifiMenu.SetItemValue(WifiOption3, 0);
          // WifiMenu.value[WifiOption3] = 0;
          Display.fillScreen(MENU_BACKGROUND);
          WifiMenu.draw();
        }
      }
}

**Comment by ConnalM** [comment]
Ah!

I knew you would have a solution! I will try this later.

Thanks so much

Connal

**Comment by KrisKasprzak** [comment]
Updating menu items can be accomplished in 2 ways 

1. use the SetItemValue method (not capitalization of Set)
       MenuObject.SetItemValue(ItemID, ItemValue);
2.  Or use the Value property (this will require version 4.0 or later of this library
       MenuObject.value[ItemID] = ItemValue;
